import os
import uuid
import json
from datetime import datetime, timezone
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


def write_log_entry(entry: dict):
    entries = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            entries = json.load(f)
    entries.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def get_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def classify_with_groq(text: str) -> float:
    prompt = f"""You are an AI content detection assistant. Analyze the following text and determine the likelihood that it was generated by an AI tool rather than written by a human.

Respond with ONLY a JSON object in this exact format:
{{"ai_score": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Where ai_score is:
- 1.0 = certainly AI-generated
- 0.0 = certainly human-written
- Values in between reflect uncertainty

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    raw = response.choices[0].message.content.strip()
    parsed = json.loads(raw)
    return float(parsed["ai_score"])

def compute_stylometric_score(text: str) -> float:
    import re
    import math

    # split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    # metric 1: sentence length variance (higher variance = more human)
    if len(sentences) > 1:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        variance = sum((l - mean) ** 2 for l in lengths) / len(lengths)
        std_dev = math.sqrt(variance)
        # normalize: 0 variance = AI-like (score 1.0), high variance = human (score 0.0)
        variance_score = 1.0 - min(std_dev / 10.0, 1.0)
    else:
        variance_score = 0.8  # single sentence = lean AI-like, uncertain

    # metric 2: type-token ratio (lower TTR = more AI-like)
    words = text.lower().split()
    if len(words) > 0:
        ttr = len(set(words)) / len(words)
        # low TTR = AI, high TTR = human
        # invert so high score = AI-like
        ttr_score = 1.0 - min(ttr, 1.0)
    else:
        ttr_score = 0.5

    # metric 3: punctuation density (lower = more AI-like)
    punct_marks = sum(1 for c in text if c in '—…()[];:\'\"')
    punct_density = punct_marks / max(len(text), 1)
    # low density = AI-like (score 1.0), high density = human (score 0.0)
    punct_score = 1.0 - min(punct_density * 20, 1.0)

    # average the three metrics
    style_score = (variance_score + ttr_score + punct_score) / 3.0
    return round(style_score, 4)

def combine_scores(llm_score: float, style_score: float) -> float:
    # 60% LLM signal, 40% stylometric signal (as defined in planning.md)
    return round((0.6 * llm_score) + (0.4 * style_score), 4)

def generate_label(confidence: float) -> str:
    if confidence > 0.70:
        return (
            "⚠ Likely AI-generated\n"
            "Our analysis found strong indicators that this content may have been generated by an AI tool.\n"
            "This label reflects automated analysis and may not be accurate. If you created this work yourself,\n"
            "you can submit an appeal and a human reviewer will take a closer look."
        )
    elif confidence >= 0.45:
        return (
            "◐ Analysis inconclusive\n"
            "Our analysis found mixed signals — this content has some characteristics of AI-generated text\n"
            "and some characteristics of human writing. No strong determination was made.\n"
            "If you feel this assessment is inaccurate, you can submit an appeal."
        )
    else:
        return (
            "✓ Appears human-written\n"
            "Our analysis found no strong indicators of AI generation in this content.\n"
            "This label reflects automated analysis only. Attribution labels are never fully definitive."
        )
    
@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: text, creator_id"}), 400

    text = data["text"]
    creator_id = data["creator_id"]
    content_id = str(uuid.uuid4())

    llm_score = classify_with_groq(text)
    style_score = compute_stylometric_score(text)
    confidence = combine_scores(llm_score, style_score)
    label = generate_label(confidence)

    attribution = "likely_ai" if confidence >= 0.5 else "likely_human"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "style_score": style_score,
        "label": label,
        "status": "classified",
        "event_type": "classification",
    }
    write_log_entry(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "style_score": style_score,
        "label": label,
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: content_id, creator_reasoning"}), 400

    content_id = data["content_id"]
    creator_reasoning = data["creator_reasoning"]

    entries = get_log()

    # find the original classification entry
    original = None
    for entry in entries:
        if entry["content_id"] == content_id and entry["event_type"] == "classification":
            original = entry
            break

    if not original:
        return jsonify({"error": "content_id not found"}), 404

    # update status in the log
    for entry in entries:
        if entry["content_id"] == content_id:
            entry["status"] = "under_review"

    # append appeal entry
    appeal_entry = {
        "content_id": content_id,
        "creator_id": original["creator_id"],
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "event_type": "appeal",
        "original_attribution": original["attribution"],
        "original_confidence": original["confidence"],
        "appeal_reasoning": creator_reasoning,
        "status": "under_review",
    }
    entries.append(appeal_entry)

    # write everything back
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)

    return jsonify({
        "message": "Appeal received. Your submission is now under review.",
        "content_id": content_id,
        "status": "under_review",
    })

@app.route("/log", methods=["GET"])
def log():
    return jsonify({"entries": get_log()})


if __name__ == "__main__":
    app.run(debug=True)